### ISSUE TITLE
Asset tracking api

### ISSUE THREAD

**Issue by kirantpatil** [amrfaissal/googlemaps-services#1]
Hi,

Does it support Asset Tracking api ?

If yes then how to use ?

Thanks.

**Comment by amrfaissal** [comment]
Hi @kirantpatil. Asset Tracking is a bit board. If I understand you correctly Asset Tracking can be achieved using the combination of multiple Google Maps services and usually you need a premium plan. This library is a Ruby client for those Google Maps APIs. Can you be more specific on what you are looking for?

**Comment by kirantpatil** [comment]
Sorry, I was under the impression that there might be Asset Tracking API. Now I have clear picture. Thanks.
