### ISSUE TITLE
Default client read_timeout may be too low?

### ISSUE THREAD

**Issue by kevgrig** [amrfaissal/googlemaps-services#3]
The [default client read_timeout is 1 second](https://github.com/amrfaissal/googlemaps-services/blob/master/lib/googlemaps/services/client.rb#L48) and this might be too aggressive. I tried the demo and immediately got `HTTP::TimeoutError: Read timed out after 1 seconds`. Setting `read_timeout: 5` in `GoogleClient.new` solved my issues. What do you think about increasing the default read_timeout to 5 seconds?

Thanks very much for this project!

**Comment by amrfaissal** [comment]
Hi @kevgrig. Good catch! I did get that error a few times ago and forgot to increase the default timeout. I will change it. Glad the library helped!
