### ISSUE TITLE
Error: undefined method `+' for nil:NilClass with OVER_QUERY_LIMIT response

### ISSUE THREAD

**Issue by nerfologist** [amrfaissal/googlemaps-services#6]
Hello, I'm using this nice library to query the Google geocoding API, and I just went over the query limit of 2500 requests/day. Immediately, in the middle of my script, I started getting errors such as this:

```
undefined method `+' for nil:NilClass
  googlemaps-services-1.4.7/lib/googlemaps/services/client.rb:170:in `rescue in request'
  googlemaps-services-1.4.7/lib/googlemaps/services/client.rb:150:in `request'
  googlemaps-services-1.4.7/lib/googlemaps/services/geocoding.rb:60:in `query'
```

This is generated when responses such as the following are received:
```
status: 200 OK
body:
{
    "error_message": "You have exceeded your daily request quota for this API.",
    "results": [],
    "status": "OVER_QUERY_LIMIT"
}
```
I assume it's related to `retry_counter` being `nil` (declared as a param with a default value of `nil` in `lib/googlemaps/services/client.rb:102` and incremented in the `rescue` block  at line 170 in the same file.

Do you think `retry_counter` should have a default value of `0` instead?

Thanks for your library, HTH

**Comment by amrfaissal** [comment]
Hi @nerfologist. Good catch! the `retry_counter` should be set to zero by default instead of nil.
Thanks.
